### ISSUE TITLE
Interrupt sometimes causes segmentation fault

### ISSUE THREAD

**Issue by chris-martin** [cachix/cachix#75]
When I stop `cachix push` with ctrl+C, somewhere around half the time it terminates with a segmentation fault.

```
chris@cubby ~ ❯❯❯ echo /nix/var/nix/profiles/system | cachix push chris-martin
pushing /nix/store/b0zlxla7dmy1iwc3g459rjznx59797xy-binutils-2.28.1
pushing /nix/store/bm7pb1s7rx1ad80706b5xqrznq7fgpgx-gcc-7.3.0
pushing /nix/store/3v8p0pvcplr3bfvrnh4fyqrqk2ddyl6f-ghc-8.2.2
pushing /nix/store/pxy47wnmlfr4hjcvldv7ggk34skpgaw6-libxml2-2.9.7
^C
user interrupt
fish: Process 30323, “cachix” “echo /nix/var/nix/profiles/syst…” terminated by signal SIGSEGV (Address boundary error)
```

I haven't seen any consequences of this so far, but reporting just in case, since it seems indicative of a problem.

**Comment by domenkozar** [comment]
This might be worse or better with https://github.com/cachix/cachix/pull/79

**Comment by domenkozar** [comment]
Got a core dump:

```
(gdb) bt
#0  0x00007fc92578b7eb in bt_skip_func () from /nix/store/chf54cl12ifswf6swh7kxpif477drihi-xz-5.2.3/lib/liblzma.so.5
#1  0x00007fc92578c558 in lzma_mf_bt4_skip () from /nix/store/chf54cl12ifswf6swh7kxpif477drihi-xz-5.2.3/lib/liblzma.so.5
#2  0x00007fc92578ef48 in lzma_lzma_optimum_normal () from /nix/store/chf54cl12ifswf6swh7kxpif477drihi-xz-5.2.3/lib/liblzma.so.5
#3  0x00007fc92578d64d in lzma_lzma_encode () from /nix/store/chf54cl12ifswf6swh7kxpif477drihi-xz-5.2.3/lib/liblzma.so.5
#4  0x00007fc925794d95 in lzma2_encode () from /nix/store/chf54cl12ifswf6swh7kxpif477drihi-xz-5.2.3/lib/liblzma.so.5
#5  0x00007fc92578adf4 in lz_encode () from /nix/store/chf54cl12ifswf6swh7kxpif477drihi-xz-5.2.3/lib/liblzma.so.5
#6  0x00007fc925782e8a in block_encode () from /nix/store/chf54cl12ifswf6swh7kxpif477drihi-xz-5.2.3/lib/liblzma.so.5
#7  0x00007fc925784555 in stream_encode () from /nix/store/chf54cl12ifswf6swh7kxpif477drihi-xz-5.2.3/lib/liblzma.so.5
#8  0x00007fc925780551 in lzma_code () from /nix/store/chf54cl12ifswf6swh7kxpif477drihi-xz-5.2.3/lib/liblzma.so.5
#9  0x00000000004b8ba2 in ?? ()
#10 0x00000000004b7cf6 in ?? ()
#11 0x0000000000000000 in ?? ()
```

**Comment by domenkozar** [comment]
So I've managed to write minimal reproducable test case:

```haskell
#!/usr/bin/env nix-shell
#!nix-shell -i "ghc -o foo -threaded -rtsopts -with-rtsopts=-N" -p "haskellPackages.ghcWithPackages (pkgs: with pkgs; [async lzma bytestring lzma-conduit cryptonite conduit-combinators])"

import Crypto.Random
import Control.Concurrent.Async
import Control.Exception (bracket_)
import Data.ByteString.Lazy (fromStrict)
import qualified Data.ByteString as BS
import Data.Conduit.Lzma (compress)
import Data.Conduit
import Data.Conduit.Combinators (sinkFile, sourceLazy)


main = replicateConcurrently_ 20 $ do
  result <- getRandomBytes 1000000 :: IO BS.ByteString
  runConduitRes $ sourceLazy (fromStrict result)
             .| compress Nothing
             .| sinkFile "/dev/null"
```

If I compile this and run it like so I can reproduce:

```
$ while true; do ./foo& sleep 0.5; pkill -SIGINT foo; done
[1] 4912
[2] 4988
[1]-  Interrupt               ./foo
[3] 5027
[2]-  Segmentation fault      ./foo
[4] 5083
[5] 5137
[3]   Interrupt               ./foo
[6] 5171
[4]   Interrupt               ./foo
[5]-  Segmentation fault      ./foo
[7] 5250
[8] 5286
^C[6]   Interrupt               ./foo
```
It segfaults consistently on nixpkgs commit d3a63b2b788aa2c9f5436953e7678032949240f2, but upgrading to 1539167d215841a966b8395c1025d66812d63d31 there's no more segfault.

In between those two commits, LTS was bumped so my assumption is that GHC 8.4.x fixes some SIGINT handlings.

Given that Cachix now uses TLS-12, I will close this and everyone hitting this bug should just upgrade to latest cachix version. If that doesn't resolve the segfault, please shout :-)
